export const AUTH = {
  GENERATE_OTP: '/api/v1/user/login/otp',
  VERIFY_OTP: '/api/v1/user/login/verifyOtp',
  GET_LOGIN_DETAILS: '/api/v1/user/login',
  LOGOUT_USER: '/api/v1/user/logout',
  SEND_OTP: '/api/v1/user/sendOtp',
  DETECT_ACCOUNT: '/api/v1/user/forgot-password/detect-user',
  TERMS_AND_CONDITIONS: '/api/v1/cms/pageInfo/terms-of-use',
  FORGOT_ACCOUNT_SEND_OTP: '/api/v1/user/forgot-password/send-otp',
  FORGOT_ACCOUNT_VERIFY_OTP: '/api/v1/user/forgot-password/verify-otp',
  RESET_PASSWORD: '/api/v1/user/forgot-password/change',
  SIGNUP: '/api/v1/user/signup',
  GET_BONUS: '/api/v1/bonus/userBonusMaster/user/get',
  GET_USER_NAME: '/api/v1/user/account/info',
  UPDATE_USER_NAME: '/api/v1/user/usernameUpdate',
  VALIDATE_PROMO_CODE: '/api/v1/user/validateCode',
  DISPUTE_RAISED: '/api/v1/user/raisedispute2',
  GEO_USER_LOCATION: '/api/v1/website/geoIp/block',
  SEND_LAT_AND_LONG: '/api/v1/website/geoIp/getLocationByLatLong',
  UPDATE_AVATAR: '/api/v1/game/update-avatar'
};

export const HAND_HISTORY = {
  HAND_HISTORY_DATA: '/pokerrest/emailHandHistory/v1/handHistoryData'
};

export const UrlConstant = {
  VIP_TERMS: '/api/v1/cms/vip_terms_api',
  POKER_LIST: '/api/v1/game/pokerList', // node www - NOT IN USE
  RING_LIST: '/api/v1/game/ringList',
  MTT_LIST: '/api/v1/game/mttList',
  GET_TABLE_LIST: '/api/v1/game/tableList',
  LOBBY_LOGOUT_NEW: '/api/v1/user/logout',
  SERVER_TIME: '/api/v1/game/serverTimeinMs',
  FORGOT_PASSWORD: '/api/v1/user/forgot-password/detect-user',
  FORGOT_PASSWORD_OTP: '/api/v1/user/forgot-password/send-otp',
  FORGOT_PASSWORD_OTP_VERIFY: '/api/v1/user/forgot-password/verify-otp',
  FORGOT_PASSWORD_GET: '/api/v1/user/forgot-password/change',
  VERSION_CHECK_NODE: '/api/v1/website/newDeviceVersion/',
  GET_LOGIN_SESSIONID: '/api/v1/user/login',
  GET_LOGIN_OTP: '/api/v1/user/login/otp',
  SEND_LOGIN_OTP: '/api/v1/user/login/sendOtp',
  VERIFY_LOGIN_OTP: '/api/v1/user/login/verifyOtp',
  GET_SIGNUP_OTP: '/api/v1/user/register/send-otp',
  VERIFY_SIGNUP_OTP: '/api/v1/user/register',
  UPDATE_USERNAME: '/api/v1/user/username/update',
  CHANGE_PASSWORD: '/api/v1/user/changePassword',
  FEATURED_TAB: '/api/v1/game/featuredTourney/list',
  TOURNEY_DETAILS: '/api/v1/game/gamewinnerList',
  MY_PROFILE_PAGE: '/my-account',
  LEADERBOARD_MENU_ITEM_URL:
    '/api/v1/gamification/contests/challenges/notification/count?showLeaderBoard=1',
  LEADERBOARD_ITEM_BASE_URL: '/cashierionic/leaderboard',
  ACCOUNT_PATH: '/my-account?tab=summary',
  REDEEM_PATH: '/my-account/redeem-chips',
  BUY_CHIPS_PATH: '/ngaccount/web/add-money', // for mobile
  TOURNEY_RULE: '/onlinepoker/assets/rule.xml?version=',
  QUOTES_XML: '/onlinepoker/assets/ngxquotes.xml?version=',
  GET_MY_TICKETS_DATA: '/api/v1/user/ticket/info',
  TOURNEY_TICKET_CLAIM: '/claimTicket.html',
  OLD_MOBILE_CLIENT: '/home/openGameDesktopWindow/poker?ng=0',
  MARQUEE_DATA_URL: '/onlinepoker/assets/LowerBanner.xml',
  LOBBY_PROMOTIONS_URL: '/api/v1/cms/banner/get-banners-v2',
  MTTLOBBY_BANNER_URL: '/get_mttlobby_banner',
  EXE_URL: '/api/v1/website/downloadUrl',
  NO_OF_HANDS_URL: '/api/v1/game/noOfHands',
  VIDEO_REPLAY_URL: '/ngVideoReplay/Replay',
  HHR_URL: '/HHR',
  LEDGER_URL: '/ledger',
  REDEEM_URL: '/user-redeem',
  HISTORY_URL: '/user-history',
  NG_BUY_CHIPS_URL: '/cashierionic/game/add-money', // for desktop
  NG_CASHIER_URL: '/cashierionic/game/account', // for desktop
  NG_CASHIER_MYTICKETS_URL: '/cashierionic/game/account/mytickets',
  NG_CASHIER_MYTICKETS_OFFER_URL: '/cashierionic/game/account/mytickets/offers',
  GET_USER_STATS: '/cashierionic/user-stats',
  GEO_VALIDATION_URL: '/api/v1/website/geoIp/block',
  GET_LOCATION_LAT_LONG: '/api/v1/website/geoIp/getLocationByLatLong',
  COMMON_POKERSERVICE_URL: '/PokerService/user/getCategorizedUsers', // for desktop
  RECOGNIZED_USER_DATA_URL: '/PokerService/user/getRecognizedUserData', // for desktop
  CHECK_PROFILE_INFO: '/redeem_api/checkProfileInfo',
  TERM_OF_USE: '/api/v1/cms/pageInfo/terms-of-use',
  RAISE_DISPUTE: '/api/v1/user/raisedispute',
  PRIZE_STRUCTURE_URL: '/PokerService/tourney/getmttPrizeStructure',
  RABBIT_DATA_URL: '/pokerrest/rabbithunt/v1/getdata',
  RABBIT_TRANSFER_URL: '/pokerrest/rabbithunt/v1/transferchips',
  FIND_PLAYER_TOURNEY_URL: '/pokerrest/search/v1/searchTourneyListByUserName',
  TOURNEY_SCHEDULE_URL: '/api/v1/game/tournament-schedule',
  TOURNEY_SCHEDULE_XLS_DOWNLOAD: '/games/downloadPokerTournamentCalendarXls',
  TOURNEY_SCHEDULE_PDF_DOWNLOAD: '/games/downloadTournamentCalendarPdf?game=poker',
  VIP_TO_REAL_INFO_URL: '/PokerService/vipconversion/viptoRealInfo',
  VIP_TO_REAL_CONVERSION: '/PokerService/vipconversion/viptoRealConversion',
  GAME_NOTICE: '/ngPoker/assets/resources/gameNotice.json',
  REDEEM_API_VIPCHIPS: '/redeem_api/viptoreal',
  BLIND_STRUCTURE: '/api/v1/game/blindStructure?blindTypeId=',
  WINNERS_SNG: '/api/v1/game/winnerDetails?tableId=',
  ADVANTAGE_SERVICE: '/advantageAndStore/v1',
  BUY_STORE_ITEM: '/buyStoreItem',
  VERSION_CHECK: '/app-device-version',
  TUTORIAL_URL: '/interactive-tutorial',
  REDEEM_IB: '/claimIB',
  VALIDATE_LOYALTY_SFS_TOKEN: '/advantageAndStore/validateSfsToken',
  CHROME_UPDATE: '/ngPoker/assets/resources/chromeUpdate.json',
  GET_CHALLENGE_CARD: '/api/v1/gamification/hitTheCard/user/challenge/cards',
  CONTEST_DETAILS: '/cashierionic/contest',
  CONTEST_MOB_SUBMENU_URL: '/api/v1/gamification/contests/challenges/notification/count',
  CONTEST_NOTIFI_MOB_SUBMENU_URL: '/api/get-current-challenges/v4',
  CONTEST_BAR_DATA_URL: '/api/v1/gamification/cgc/progressBar',
  CHALLENGES_IFRAME_URL: '/nujChallenges',
  CHALLENGES_CHECKUSERIFNEW: '/challenges/checkUserIfNew',
  CHALLENGES_CHECK_NUJ: '/challenges/checkNUJ',
  DOWNLOAD_HAND_HISTORY_URL: '/pokerrest/emailHandHistory/v1/handHistoryData',
  GET_ALL_NOTES: '/PokerService/notes/getall',
  SAVE_NOTES: '/PokerService/notes/save',
  ADD_NOTES: '/PokerService/notes/add',
  GET_NOTES: '/PokerService/notes/get',
  DELETE_NOTES: '/PokerService/notes/delete',
  NET_TDS_CONTENT_FLAG: '/PokerService/vipconversion/flagsNewTdsAndContent',
  SESSION_CONTESTS_ENROLL: '/api/v1/gamification/lobby/contests/enrollStatus',
  SESSION_CONTESTS_REGISTER: '/api/v1/gamification/league/register',
  CONTESTS_CLAIM_API: '/api/v1/gamification/contest/claim',
  GET_USER_BONUS_MASTER: '/api/v1/bonus/userBonusMaster/user/get',
  GET_DECRYPT_KEY: '/api/v1/website/appInitData/',
  BOT_DETECT_API: '/api/v1/game/clientEventInfo',
  PRIVATE_TABLE_API: '/api/v1/game/privateTable/user/getAll',
  SIGNUP_BONUS_API: '/signup-promotion',
  GET_HUD_USER_STATS: '/pokerrest/hud/myStats',
  MY_PROFILE_NEW_URL: '/cashierionic/game/profile',
  MY_PROFILE_openDocKyc_URL: '/cashierionic/game/profile/document-verification/kyc',
  MY_PROFILE_openSelfie_URL: '/cashierionic/game/profile/document-verification/selfie',
  MY_PROFILE_openPanKyc_URL: '/cashierionic/game/profile/document-verification/pan',
  MY_PROFILE_openBank_URL: '/cashierionic/game/profile/withdrawal-method/add-bank',
  USER_LOGIN_SIGNUP: '/signin',
  GET_EXE_BOT_NAME: '/api/v1/website/exe-init-data',
  USER_AUTO_LOGIN: '/api/v1/user/auto/login',
  ROOM_DATA_UPDATE: '/gameSocketService/getRoomDataUpdate',
  ROW_CLICK_DATA: '/gameSocketService/getRowClickData',
  USER_ACCOUNT_INFO: '/gameSocketService/lobby/getUserAccount',
  FAQSURL: 'https://adda52.zendesk.com/hc/en-us',
  RAF_BASE_URL: '/cashierionic/ref',
  CLOSE_SPIN_WHEEL: '/api/v1/bonus/stw/close',

  // ----- Profile | Personal Details APIs | Starts Here -----
  NEW_PROFILE: '/api/v1/user/profileNew',
  KYC_DETAILS: '/api/v1/redeem/user/kyc/status',
  ALTERNATE_MOBILE_NUMBER_SEND_OTP: '/api/v1/user/sendMobileOtp',
  ALTERNATE_MOBILE_NUMBER_VERIFY_OTP: '/api/v1/user/verifyMobileOtp',
  SEND_EMAIL_OTP: '/api/v1/user/sendEmailOtp',
  SEND_EMAIL_VERIFY_OTP: '/api/v1/user/verifyEmailOtp',
  SAVE_USER_PROFILE_DETAILS: '/api/v1/user/profile',
  // ----- Profile | Personal Details APIs | Ends Here -----

  // ----- Profile | Document Verification APIs | Starts Here -----
  GET_PAN_DETAILS: '/api/v1/redeem/user/pan/details',
  UPLOAD_PAN_DETAILS: '/api/v1/redeem/user/pan/upload',
  UPLOAD_KYC_DETAILS: '/api/v1/redeem/user/kyc/upload',
  KYC_UPLOAD: '/api/v1/redeem/user/kyc/upload',
  KYC_DOC_LIST: '/api/v1/redeem/user/kycdoc/list',

  // ----- Profile | Document Verification APIs | Ends Here -----
  UPLOAD_BANK_DETAILS: '/api/v1/redeem/user/bank/verification',
  IFSC_DETAILS: '/api/v1/redeem/user/bank/getIfscDetails',
  BANK_LIST: '/api/v1/redeem/user/bank/list',
  DEFAULT_BANK: '/api/v1/redeem/user/bank/default',

  GET_SAVED_CARDS: '/api/v1/purchase/saved-cards',
  DELETE_SAVED_CARDS: '/api/v1/purchase/saved-cards',

  UPI_VALIDATE: '/user/profile/vpa/validate',
  UPI_VERIFY: '/user/profile/vpa/verify',

  GET_KYC_DOCS: '/api/v1/redeem/user/kyc/list',
  GET_AADHAR_REDIRECT_DATA: '/api/v1/redeem/user/aadhar/profile',
  SELFIE_UPLOAD: '/api/v1/redeem/user/selfie/upload',
  SELFIE_DETAILS: '/api/v1/redeem/user/selfie/status'
};

export const CONTACT_US = {
  GUEST_CONTACT_URL: 'https://fullhouse.adda52poker.com/customer-support'
};
